services:
  web1:
    build: ./server
    environment:
      - SERVER_ID=web1
  
  web2:
    build: ./server
    environment:
      - SERVER_ID=web2
  
  web3:
    build: ./server
    environment:
      - SERVER_ID=web3
  
  loadbalancer:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web1
      - web2
      - web3
  
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    depends_on:
      - prometheus