events {}

http {
    upstream backend {
        server web1:3000 weight=3;
        server web2:3000 weight=2;
        server web3:3000 weight=1;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
        }
    }
}